print()
print('Please enter the following:')
print()
adj1 = input('Adjective: ')
animal = input('Animal: ')
verb1 = input('Verb: ')
exclam = input('Exclamation: ')
verb2 = input('Verb: ')
verb3 = input('Verb: ')
name1 = input('Name: ')
name2 = input('Name: ')
obj1 = input('Object: ')
name3 = input('Female Name: ')
adj2 = input('Adjective: ')
verb4 = input('Verb: ')
obj2 = input('Object: ')
print()
print('Your story is:')
print()
print('The other day, I was really in trouble. It all started when I saw a very\n' + adj1.lower() + ' ' + animal.lower() + ' ' + verb1.lower() +  ' down the hallway. "' + exclam.capitalize() + '!" I yelled. But all \nI could think to do was to ' + verb2.lower() + ' over and over. Miraculously,\nthat caused it to stop, but not before it tried to ' + verb3.lower() + '\nright in front of my family. My wife said "' + name1.capitalize() + ', why is ' + name2.capitalize() + ' eating a\n' + obj1.lower() + ' in the closet?" I replied, "' + name3.capitalize() + ', she is ' + adj2.lower() + '."\nThen I decided to ' + verb4.lower() + ' a ' + obj2.lower() + '.')
print()